# AKS values for notification-service.

name: notification-service
port: 8083

config:
  SPRING_DATASOURCE_USERNAME: "flexhub"
  SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: "PLAIN"

envFromSecret:
  - name: SPRING_DATASOURCE_PASSWORD
    secretName: postgres-postgresql
    key: password
  - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
    secretName: flexhub-secrets
    key: eventhubs-jaas-config

azureWorkloadIdentity:
  enabled: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
